services:
  postgres:
    image: postgres:16-alpine
    container_name: vixy-crm-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vixy_crm
    ports:
      - '5433:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: vixy-crm-redis
    ports:
      - '6381:6379'
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:
